### ISSUE TITLE
SRS Presentation Slides Review

### ISSUE THREAD

**Issue by kypss94132** [kypss94132/CAS741_YiLeng-Chen#2]
Dear Dr. Smith,

I am going to have an SRS presentation in tomorrow's class. Here are [my presentation slides](https://github.com/kypss94132/CAS741_YiLeng-Chen/blob/main/docs/Presentations/SRSPresentation%20.pptx). 
I am looking forward to receiving some feedback. Thank you!

**Comment by smiths** [comment]
Feedback:

- this is too simple a theoretical model - you only have one equation - the source you are using has more models than just this one.  You should have more models in your planned software.
- you don't have all of the needed information for the definition of the equation.  You should look at the paper that is cited in your source.  (The reference is to paper 16.)  The definition for M3 is ambiguous.  How much rain is needed to count the month a month when rain occurs?
- Calculations is spelled incorrectly
- there aren't enough assumptions - for example, you are also assuming that the thickness of the clad for the concrete doesn't matter.

You should target a project scope similar to [GlassBR](https://jacquescarette.github.io/Drasil/examples/glassbr/SRS/srs/GlassBR_SRS.html).  The GlassBR example is similar to yours in that it is made up of experimentally determined equations, rather than being directly based on physics.  The equations given in Section 3 of your source are more interesting than the single equation you selected.

You also aren't limited to just this one source.  You might find a more modern resource that is more helpful for your goal.  A quick Google search found a more [modern paper](https://www.sciencedirect.com/science/article/pii/S0008884602010347) that might be easier for you to read.
